/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hlq_utils_ChangeUtils */

#ifndef _Included_hlq_utils_ChangeUtils
#define _Included_hlq_utils_ChangeUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef hlq_utils_ChangeUtils_zhengchang
#define hlq_utils_ChangeUtils_zhengchang 0L
#undef hlq_utils_ChangeUtils_luoli
#define hlq_utils_ChangeUtils_luoli 1L
#undef hlq_utils_ChangeUtils_dashu
#define hlq_utils_ChangeUtils_dashu 2L
#undef hlq_utils_ChangeUtils_jingsong
#define hlq_utils_ChangeUtils_jingsong 3L
#undef hlq_utils_ChangeUtils_gaoguai
#define hlq_utils_ChangeUtils_gaoguai 4L
#undef hlq_utils_ChangeUtils_kongling
#define hlq_utils_ChangeUtils_kongling 5L
/*
 * Class:     hlq_utils_ChangeUtils
 * Method:    change
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_hlq_utils_ChangeUtils_change
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
